name: Lime Studios
title: Lime Studios
markdown: redcarpet
icon: "/assets/img/site/icon/logo128.png"
exclude: ["node_modules", "gulpfile.js", "package.json"]

home-nav: [
  {link: "/", text: "Home"},
  {link: "/page/about", text: "About"},
  {link: "/portfolio", text: "Portfolio"},
  {link: "/blog", text: "Blog"},
  {link: "/page/contact", text: "Contact"},
  {link: "/page/presskit", text: "Press"}
]

permalink: /:categories/:title/
post_dirs: false
